[book]
authors = ["CRIB group, okawak"]
language = "en"
multilingual = false
src = "src"
title = "Manual for CRIB artemis"

[output.html]
mathjax-support = true
git-repository-url = "https://github.com/CRIB-project/artemis_crib"
git-repository-icon = "fa-github"
additional-css = ["last-changed.css"]
additional-js = ["mermaid.min.js", "mermaid-init.js"]

[preprocessor.last-changed]
command = "mdbook-last-changed"
renderer = ["html"]

[preprocessor.mermaid]
command = "mdbook-mermaid"
