#!/bin/sh

# This script defines functions for interacting with the Artemis environment.
# It is intended to be sourced in your .bashrc or .zshrc file.

# Function to display usage information
art_usage() {
  cat <<EOF
USAGE:
    1. artlogin

        Enter the Artemis environment
        > artlogin
        This is for the default (shared) user
        > artlogin username
        Create a new user or enter personal environment

        After this command, the 'acd' alias is available
        > acd
        'acd' changes directory to your Artemis work directory

    2. a

        Start Artemis
        NOTE: Need to execute after 'artlogin' command
        > artlogin
        > a

        This can be used when you want to use macro files
        > a 'macro/somefile.C("hoge")'

    3. art_usage (this)

        Show the USAGE
EOF
}

# Define functions to interact with Artemis

# Function to start Artemis with proper display settings
a() {
  # Check if 'artemislogon.C' exists in the current directory
  if [ ! -e "artemislogon.C" ]; then
    printf "\033[1ma\033[0m: 'artemislogon.C' not found\n"
    return 1
  fi

  # Determine if the user is connected via SSH and adjust DISPLAY accordingly
  if [ -z "${SSH_CONNECTION:-}" ]; then
    # Not connected via SSH
    artemis -l "$@"
  elif [ -f ".vncdisplay" ]; then
    # Connected via SSH and .vncdisplay exists
    DISPLAY=":$(cat .vncdisplay)" artemis -l "$@"
  else
    # Connected via SSH without .vncdisplay
    artemis -l "$@"
  fi
}

# Function to set up the Artemis environment for the default experiment
artlogin() {
  export ART_EXP_NAME="${EXP_NAME}"

  # Check if the experiment configuration file exists
  if [ -e "${HOME}/art_analysis/.conf/${ART_EXP_NAME}.sh" ]; then
    # Load the experiment configuration
    . "${HOME}/art_analysis/.conf/${ART_EXP_NAME}.sh"
  else
    printf "\033[1martlogin\033[0m: Environment for '%s' not found. Create it using 'artnew' command.\n" "${ART_EXP_NAME}"
    return 1
  fi

  # Set the username in an environment variable
  ARTLOGIN_USERNAME="${1:-}"
  export ARTLOGIN_USERNAME

  # Source the general artlogin script
  . "${HOME}/art_analysis/.conf/artlogin.sh"
}

# Function to set up the Artemis environment for the old experiment
artlogin2() {
  export ART_EXP_NAME="${EXP_NAME_OLD}"

  # Check if the experiment configuration file exists
  if [ -e "${HOME}/art_analysis/.conf/${ART_EXP_NAME}.sh" ]; then
    # Load the experiment configuration
    . "${HOME}/art_analysis/.conf/${ART_EXP_NAME}.sh"
  else
    printf "\033[1martlogin\033[0m: Environment for '%s' not found. Create it using 'artnew' command.\n" "${ART_EXP_NAME}"
    return 1
  fi

  # Set the username in an environment variable
  ARTLOGIN_USERNAME="${1:-}"
  export ARTLOGIN_USERNAME

  # Source the general artlogin script
  . "${HOME}/art_analysis/.conf/artlogin.sh"
}
