name: Build and Deploy Docs

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # install Rust
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      # install and build mdBook
      - name: Install mdBook
        run: cargo install mdbook
      - name: Build mdBook
        working-directory: ./docs/guide
        run: mdbook build

      # install and build Doxygen
      - name: Install Doxygen 1.12.0
        run: |
          curl -LO https://www.doxygen.nl/files/doxygen-1.12.0.linux.bin.tar.gz
          tar -xzf doxygen-1.12.0.linux.bin.tar.gz
          sudo mv doxygen-1.12.0/bin/doxygen /usr/local/bin/doxygen
      - name: Check Doxygen version
        run: doxygen --version

      - name: Install graphviz
        run: sudo apt-get install -y graphviz
      - name: Set STRIP_FROM_PATH dynamically
        working-directory: ./docs/reference
        run: |
          echo "STRIP_FROM_PATH = $GITHUB_WORKSPACE" >> Doxyfile
          tail -n 1 Doxyfile
      - name: Generate Doxygen documentation
        working-directory: ./docs/reference
        run: doxygen Doxyfile

      # combine outputs to public directory
      - name: Combine outputs
        run: |
          rm -rf public
          mkdir -p public
          cp -r docs/guide/book/* public/
          cp -r docs/reference/html public/reference/

      # Copy the script files
      - name: Copy script files
        run: |
          cp -r docs/scripts public/

      # deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          keep_files: true
          user_name: "GitHub Actions"
          user_email: "actions@github.com"
