name: Build and Deploy Docs

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # install Rust
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      # install and build mdBook
      - name: Install mdBook
        run: cargo install mdbook
      - name: Build mdBook
        working-directory: ./docs/guide
        run: mdbook build

      # install and build Doxygen
      - name: Install Doxygen
        run: sudo apt-get install -y doxygen graphviz
      - name: Generate Doxygen documentation
        working-directory: ./docs/reference
        run: doxygen Doxyfile

      # combine outputs to public directory
      - name: Combine outputs
        run: |
          rm -rf public
          mkdir -p public
          cp -r docs/guide/book/* public/
          cp -r docs/reference/html public/reference/

      # Copy the script files
      - name: Copy script files
        run: |
          cp -r docs/scripts public/

      # deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          keep_files: true
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
